"""add departments table

Revision ID: 2830887f108a
Revises: 50717b3f5f79
Create Date: 2024-01-23 15:29:46.616761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2830887f108a'
down_revision: Union[str, None] = '50717b3f5f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('tbl_departments',
    # sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('department_name', sa.String(length=50), nullable=False),
    # sa.PrimaryKeyConstraint('department_id')

    #op.add_column('tbl_courses', sa.Column('department_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'tbl_courses', 'tbl_departments', ['department_id'], ['department_id'])
    # ### end Alembic commands ###
    pass



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_courses', type_='foreignkey')
    op.drop_column('tbl_courses', 'department_id')
    op.drop_table('tbl_departments')
    # ### end Alembic commands ###
