"""added employee model

Revision ID: 2eec3067123d
Revises: 6fe4d863181b
Create Date: 2024-02-15 12:03:32.372120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eec3067123d'
down_revision: Union[str, None] = '6fe4d863181b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_employees',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_fname', sa.String(length=45), nullable=False),
    sa.Column('employee_lname', sa.String(length=45), nullable=False),
    sa.Column('employee_dept_id', sa.Integer(), nullable=False),
    sa.Column('employee_title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_dept_id'], ['tbl_departments.department_id'], ),
    sa.ForeignKeyConstraint(['employee_title_id'], ['tbl_titles.title_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_employees')
    # ### end Alembic commands ###
