"""created titles model

Revision ID: 5e8a4ca64803
Revises: 7f37adbdfe58
Create Date: 2024-02-14 15:09:16.501927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e8a4ca64803'
down_revision: Union[str, None] = '7f37adbdfe58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_faculty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_faculty',
    sa.Column('faculty_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('faculty_fname', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('faculty_lname', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('faculty_dept_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['faculty_dept_id'], ['tbl_departments.department_id'], name='tbl_faculty_ibfk_1'),
    sa.PrimaryKeyConstraint('faculty_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
