"""fixing from rollback

Revision ID: 7f37adbdfe58
Revises: df0f3bee074a
Create Date: 2024-02-11 18:06:29.402507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f37adbdfe58'
down_revision: Union[str, None] = 'df0f3bee074a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   

    op.drop_table('tbl_employees')
    op.drop_table('tbl_titles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_titles',
    sa.Column('title_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('title_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_employees',
    sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('employee_fname', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('employee_lname', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('employee_dept_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('employee_title_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_dept_id'], ['tbl_departments.department_id'], name='tbl_employees_ibfk_1'),
    sa.ForeignKeyConstraint(['employee_title_id'], ['tbl_titles.title_id'], name='tbl_employees_ibfk_2'),
    sa.PrimaryKeyConstraint('employee_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tbl_faculty')
    # ### end Alembic commands ###
