"""initial

Revision ID: beda044df9f1
Revises: 
Create Date: 2024-01-19 17:48:32.109216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beda044df9f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('tbl_gender',
    sa.Column('gender_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('gender_id')
    )
    op.create_table('tbl_grade_levels',
    sa.Column('grade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('grade_id')
    )
    op.create_table('tbl_sections',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_name', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['tbl_courses.course_id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['tbl_grade_levels.grade_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('tbl_student',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_fname', sa.String(length=45), nullable=True),
    sa.Column('student_lname', sa.String(length=45), nullable=True),
    sa.Column('student_gender_id', sa.Integer(), nullable=True),
    sa.Column('grade_level_id', sa.Integer(), nullable=True),
    sa.Column('student_age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_level_id'], ['tbl_grade_levels.grade_id'], ),
    sa.ForeignKeyConstraint(['student_gender_id'], ['tbl_gender.gender_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('tbl_enrollments',
    sa.Column('enrollment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['tbl_sections.section_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['tbl_student.student_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_enrollments')
    op.drop_table('tbl_student')
    op.drop_table('tbl_sections')
    op.drop_table('tbl_grade_levels')
    op.drop_table('tbl_gender')
    op.drop_table('tbl_courses')
    # ### end Alembic commands ###
